#-----------------------------------#
# jShooter Framework - CONFIGURACAO #
#         by Cristiano Souza        #
#-----------------------------------#
#
# 1. gameResolution
# ----------------------------
# Redefine a resolucao de tela.
# Opcoes:
#   0 = Windowed, 640 x 480
#   1 = Windowed, 800 x 600
#   2 = Fullscreen, 800 x 600 32-bit
#
# 2. frameRate
# ----------------------------
# Muda a taxa de atualizacao do kernel.
# (minimo = 10 - maximo = 60 - recomendado = 30)
#
# 3. Configuracoes de teclado
# ----------------------------
# Definem as teclas usadas para controlar o jogo.
# Todas as chaves comecando com p1 (para o jogador 1) e p2 (para o jogador 2).
#
# 4. logFile
# ----------------------------
# Caminho e nome de arquivo para armazenar o log.
#
# 5. logLevel
# ----------------------------
# Selecao do nivel de log. Opcoes:
#   OFF = 0 (padrao)
#   ERRORS = 1
#   WARINGS = 2
#   DEBUG = 3
#
# 6. logVisible.
# ----------------------------
#   OFF = 0 (padrao)
#   ON  = 1
#
# ATENCAO: Nao ligue esta opaao, vai deixar o jogo muito mais lento.
#
# 7. matrixX e matrixY
# ---------------------------
# Tamanho (em pixels) da matriz de colisao. Padrao: matrixX = 80 e matrixY = 60.
#
# ATENCAO: modificar este valor pode causar erros no jogo.
#
# 8. rederOnScreen
# ---------------------------
# Renderiza na tela informaaaes sobre o kernel.
# OFF = 0 (padrao)
# ON  = 1
#
# 9. rederCollision
# ---------------------------
# Renderiza na tela a matriz de colisao.
# OFF = 0 (padrao)
# ON  = 1
#
# 10. lives
# ---------------------------
# Numero de vidas iniciais do jogador.
#
# 11. bgmOn
# ---------------------------
# Reproduaao de masicas durante o jogo.
# OFF = 0
# ON  = 1 (padrao)
#
# 12. effOn
# ---------------------------
# Reproduaao de efeitos sonoros durante o jogo.
# OFF = 0
# ON  = 1 (padrao)
#
# 13. cheating
# ---------------------------
# Codigos especiais (consulte o manual do jogo).
#
#Wed Oct 08 16:35:50 BRT 2025
bgmOn=1
cheating=0
effOn=1
frameRate=30
gameResolution=0
hardGame=1
lives=3
logFile=C\:/temp/Starfight_
logLevel=0
logVisible=0
matrixX=80
matrixY=60
p1ActionA=90
p1ActionB=88
p1ActionC=65
p1ActionD=83
p1Down=40
p1Left=37
p1Right=39
p1Up=38
p2ActionA=0
p2ActionB=0
p2ActionC=0
p2ActionD=0
p2Down=0
p2Left=0
p2Right=0
p2Up=0
rederCollision=0
rederOnScreen=0
