#-----------------------------------------------------
#                  J.S.H.O.O.T.E.R
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#                                               v1.0.0
#
# ARQUIVO DE CONFIGURACAO DE EFEITOS SONOROS
#
#   Este arquivo indica ao Framework quais efeitos de-
# vem ser carregadas durante a inicialização, e qual 
# deve ser o índice de acesso de cada uma.
#   Deve-se criar uma entrada para cada arquivo, obe-
# decendo a seguinte sintaxe:
# 
# FN = snd/NOMEARQUIVO.ext
#   Onde:
#   - N: Índice de acesso do arquivo de efeito no co-
# digo.
#   - NOMEARQUIVO: nome do arquivo (atenção: os nomes
# dos arquivos não podem conter espaços ou caracteres
# especiais).
#   - .ext: Extensão ou tipo do arquivo. São aceitos
# arquivos do tipo WAV, AU e AIFF. 
#
#   No topo da lista, deve ser adicionada a seguinte 
# entrada:
#
# QTY=N
# 
#   Onde N e a quantidade de efeitos que existem para 
# ser carregadas.
#-----------------------------------------------------
QTY=3
F0=snd/00_shot_p.wav
F1=snd/01_explosion_common.wav
F2=snd/02_explosion_player.wav
