#-----------------------------------------------------
#                  J.S.H.O.O.T.E.R
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#                                               v1.0.0
#
# ARQUIVO DE CONFIGURACAO DE IMAGENS
#
#   Este arquivo indica ao Framework quais imagens de-
# vem ser carregadas durante a inicializacao, e qual 
# deve ser o indice de acesso de cada uma.
#   Deve-se criar uma entrada para cada arquivo, obe-
# decendo a seguinte sintaxe:
# 
# IMGN = img/NOMEARQUIVO.ext
#   Onde:
#   - N: Indice de acesso da imagem no codigo
#   - NOMEARQUIVO: nome do arquivo (atencao: os nomes
# dos arquivos nao podem conter espacos ou caracteres
# especiais).
#   - .ext: Extensao ou tipo do arquivo. Sao aceitos
# arquivos do tipo GIF e JPG. 
#
#   No topo da lista, deve ser adicionada a seguinte 
# entrada:
#
# QTY=N
# 
#   Onde N e a quantidade de imagens que existem para 
# ser carregadas.
#-----------------------------------------------------
QTY = 26
# RESERVADO PARA O FRAMEWORK
 IMG0 = img/PAUSE.gif
 IMG1 = img/STAGECLEAR.gif
 IMG2 = img/WARNING.gif
# BASICAS
 IMG3 = img/LOGO.png
 IMG4 = img/TIRO_DIR.png
 IMG5 = img/TIRO_ESQ.png
# CENARIO
 IMG6 = img/BG_LAYER1.png
 IMG7 = img/BG_LAYER2.png
 IMG8 = img/BG_LAYER3.png
 IMG9 = img/BG_LAYER4.png
# OBJETOS 
IMG10 = img/PLAYER_SHIP_01.png
IMG11 = img/PLAYER_SHIP_02.png
IMG12 = img/PLAYER_SHIP_03.png
IMG13 = img/PLAYER_SHIP_04.png
IMG14 = img/TANQUE_01.png
IMG15 = img/TANQUE_02.png
IMG16 = img/TANQUE_03.png
IMG17 = img/HELICOPTERO_01.png
IMG18 = img/HELICOPTERO_02.png
IMG19 = img/ARVORE.png
IMG20 = img/AVIAO.png
IMG21 = img/AVIAO2_01.png
IMG22 = img/AVIAO2_02.png
IMG23 = img/CASA.png
IMG24 = img/BALAO.png
IMG25 = img/SPACE_JOQUEY.png

