#-----------------------------------------------------
#                  J.S.H.O.O.T.E.R
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#                                               v1.0.0
#
# ARQUIVO DE CONFIGURACAO DE MUSICAS
#
#   Este arquivo indica ao Framework quais musicas de-
# vem ser carregadas durante a inicializacao, e qual 
# deve ser o indice de acesso de cada uma.
#   Deve-se criar uma entrada para cada arquivo, obe-
# decendo a seguinte sintaxe:
# 
# FN = bgm/NOMEARQUIVO.ext
#   Onde:
#   - N: Indice de acesso do arquivo MIDI no codigo.
#   - NOMEARQUIVO: nome do arquivo (atencao: os nomes
# dos arquivos nao podem conter espacos ou caracteres
# especiais).
#   - .ext: Extensao ou tipo do arquivo. Sao aceitos
# apenas arquivos do tipo MIDI (extensao .mid). 
#
#   No topo da lista, deve ser adicionada a seguinte 
# entrada:
#
# QTY=N
# 
#   Onde N e a quantidade de músicas que existem para 
# ser carregadas.
#-----------------------------------------------------
QTY=3
F0=bgm/00_logo_2s.mid
F1=bgm/01_intro_122s.mid
F2=bgm/02_stage01.mid
